<a href="https://colab.research.google.com/github/mimsabiha/DSP_LAB/blob/main/Lab_Task_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([2,0,3,5])
b=np.array([1,4,1,0])
print(np.convolve(a,b))

[ 2  8  5 17 23  5  0]


In [ ]:
#convolution
lx = len(a)
ly = len(b)

s = np.zeros((lx+ly))
for m in range(lx):
  for n in range(ly):
    s[m+n]= s[m+n] + a[m]*b[n]

print(s)   


[ 2.  8.  5. 17. 23.  5.  0.  0.]


In [ ]:
y = np.correlate(a,b,mode='full')
print(y)

[ 0  2  8  5 17 23  5]


In [ ]:
#cross CORREALTE
b=np.flip(b)
lx = len(a)
ly = len(b)

s = np.zeros((lx+ly))
for m in range(lx):
  for n in range(ly):
    s[m+n]= s[m+n] + a[m]*b[n]

print(s) 

[ 0.  2.  8.  5. 17. 23.  5.  0.]


In [ ]:
#Auto CORREALTE
c=np.flip(a)
lx = len(a)
ly = len(a)

s = np.zeros((lx+ly))
for m in range(lx):
  for n in range(ly):
    s[m+n]= s[m+n] + a[m]*c[n]

print(s) 

[10.  6. 15. 38. 15.  6. 10.  0.]


In [ ]:
y = np.correlate(a,a,mode='full')
print(y)

[10  6 15 38 15  6 10]
